		<div class="bottom">
			<div class="container">
				<label>121, rue de Courcelles - 75017 Paris • 01 43 80 11 68 • Ouvert tous les jours Midis et Soirs</label> •
				<a href="https://www.facebook.com/restaurantbacino">
					<img  id="logo_facebook"  src="/ressources/images/FB-f-Logo__white_29.png" alt="facebook">
				</a>
			</div>
		</div>		
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>	
		<script src="/ressources/bootstrap/js/bootstrap.min.js"></script>
		<script src="/ressources/bootstrap/js/responsive-tabs.js"></script>
		<script src="/ressources/js/app.js"></script>
	</body>
</html>