<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Bacino</title>
		<link rel="stylesheet" href="/ressources/css/style.css" />	
		<link href="/ressources/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	</head>	
	<body>	
		<header class="top" role="header">	
			<div class="container">
				<a href="../" class="pull-left"><img  class="logo_header"  src="/ressources/images/logo/logo_couleur.png" alt="Bacino"></a>
				<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            		<span class="glyphicon glyphicon-align-justify"></span>
        		</button>
        		<nav class="navbar-collapse collapse" role="navigation">
		            <ul class="navbar-nav nav	">
		                <li><a id="menuCarte" class="menu" href="/carte/index">La Carte</a></li>
		                <li><a id="menuPhotos" class="menu" href="/site/photo" >Photos</a></li>
		                <li><a id="menuAcces" class="menu" href="/site/acces">Accès</a></li>
		                <li><a id="menuContact" class="menu" href="/site/contact">Contact</a></li>
		            </ul>
       			</nav>
       		</div>
		</header>
		