<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="description" content="Pizza, pâtes, spécialités italiennes." />
		<meta name="keywords" content="Pizza, pâtes, restaurant, italien, courcelles, paris, 17e, pizzeria, spécialités, plat du jour" />
		<title>Bacino</title>
		<style type="text/css">	</style>
		<link rel="stylesheet" href="/script/style.css" />		
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>	
	</head>
	<body>
		<div id="canvas">		
			<div id="content" style="padding:0;">
			<h1>Page d'acceuil</h1>
				<div id="haut">
					<div id="rouge">
						<div id="logo_index_div">
							<img id="logo_index" src="ressources/images/logo/logo_gris.png" alt="Bacino"></img><br>
							<h1 id="motto">Pizzas &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Pâtes &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Spécialités italiennes</h1>
						</div>

					</div>
					<div id="marquise">
						<img id="img_marquise" src="/ressources/images/marquise.png" alt="Bacino"></img>
					</div>
				</div>
				</br>
				<div id="menu">
					<a class="menu" href="/carte/index" 
						onMouseOver="$('#dessin1').css({'display':'inline'});"
						onMouseOut="$('#dessin1').css({'display':'none'});"
						>La Carte</a>
					<a class="menu" href="/site/photo"
						onMouseOver="$('#dessin2').css({'display':'inline'});"
						onMouseOut="$('#dessin2').css({'display':'none'});"
					>Photos</a>
					<a class="menu" href="/site/acces"
						onMouseOver="$('#dessin3').css({'display':'inline'});"
						onMouseOut="$('#dessin3').css({'display':'none'});"
					>Accès</a>
					<a class="menu" href="/site/contact"
						onMouseOver="$('#dessin4').css({'display':'inline'});"
						onMouseOut="$('#dessin4').css({'display':'none'});"
					>Contact</a>
				</div>
				<div id="bas">
					<img class="dessin" id="dessin1" src="/ressources/dessin1.png" alt="Carte"></img>
					<img class="dessin" id="dessin2" src="/ressources/dessin2.png" alt="Photos"></img>
					<img class="dessin" id="dessin3" src="/ressources/dessin3.png" alt="Acces"></img>
					<img class="dessin" id="dessin4" src="/ressources/dessin4.png" alt="Contact"></img>
				</div>
				</div>
			</div>
			<div id="footer">
				<label>121, rue de Courcelles - 75017 Paris • 01 43 80 11 68 • Ouvert tous les jours Midis et Soirs •</label><a href="https://www.facebook.com/restaurantbacino"><img  id="logo_facebook"  src="/ressources/images/FB-f-Logo__white_29.png"></a>
			</div>
		</div>
	</body>
</html>
