<div id="tabs">
	<ul id="tabs_list">
		<li><a class="type" id="tabs-ent" href="#tabs_entrees" title="">Starters</a></li>
		<li><a class="type" id="tabs-piz" href="#tabs_pizzas" title="">Pizzas</a></li>
		<li><a class="type" id="tabs-pat" href="#tabs_pates" title="">Pasta</a></li>
		<li><a class="type" id="tabs-pla" href="#tabs_plats" title="">Main Courses</a></li>
		<li><a class="type" id="tabs-des" href="#tabs_desserts" title="">Desserts</a></li>
		<li><a class="type" id="tabs-vin" href="#tabs_vins" title="">Wines</a></li>
	</ul>
	<div id="tabs_container">
		<div id="tabs_entrees">
			<ul>
				<li class="plat"><label  class="nom_plat" >Tomato mozzarella di buffala with basil </label><label class="recette"> </label><label class="prix">12</label></li>
				<li class="plat"><label  class="nom_plat" >Antipasti of vegetables with olive oil </label><label class="recette"> </label><label class="prix">12</label></li>
				<li class="plat"><label  class="nom_plat" >Fresh green beans salad </label><label class="recette"> </label><label class="prix">11</label></li>
				<li class="plat"><label  class="nom_plat" >Parma ham platter </label><label class="recette"> </label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Italian cooked or cured meats platter </label><label class="recette">coppa, bresaola, Parma ham </label><label class="prix">17</label></li>
				<li class="plat"><label  class="nom_plat" >Napolitan-style bruschetta </label><label class="recette"> </label><label class="prix">11</label></li>
				<li class="plat"><label  class="nom_plat" >Beef Carpaccio </label><label class="recette"> </label><label class="prix">13</label></li>
				<li class="plat"><label  class="nom_plat" >Raw salmon marinated with oil </label><label class="recette"> </label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Bacino Salad </label><label class="recette">rocket salad, Parmesan and dried tomatoes</label><label class="prix">11</label></li>
				<li class="plat"><label  class="nom_plat" >Extra-charge mozzarella ball </label><label class="recette"></label><label class="prix">5</label></li>
			</ul>
		</div>		
		<div id="tabs_pizzas">		
			<ul>
				<li class="plat"><label  class="nom_plat" >Pizza "blanche" with garlic and olive oil </label><label class="recette"> </label><label class="prix">8</label></li>
				<li class="plat"><label  class="nom_plat" >Margharita </label><label class="recette">tomato, mozzarella, black olives</label><label class="prix">13</label></li>
				<li class="plat"><label  class="nom_plat" >Napolitaine </label><label class="recette">tomato, mozarella, black olives, anchovy</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Quatre fromages </label><label class="recette">tomato, mozarella, Gorgonzola, goat and Parmesan cheeses</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Regina </label><label class="recette">tomato, mozarella, ham, mushrooms</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Quatre saisons </label><label class="recette">tomato, mozarella, black olives, ham, mushrooms, artichokes</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Al tonno </label><label class="recette">tomato, thon, black olives, capers</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Calzone </label><label class="recette">tomato, mozarella, ham, egg</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Parma </label><label class="recette">tomato, mozarella, Parma ham, fresh cream</label><label class="prix">17</label></li>
				<li class="plat"><label  class="nom_plat" >Chorizo </label><label class="recette">tomato, mozarella, chorizo, onions, egg</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Salmone </label><label class="recette">tomato, mozarella, smocked salmon, fresh cream</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Bacino </label><label class="recette">tomato, mozarella, rocket salad and fresh marinated tomatoes</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Campione </label><label class="recette">tomato, mozarella, minced meat, onions and egg</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Végétarienne </label><label class="recette">tomato, mozarella, mushrooms, courgettes and aubergines</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Orientale </label><label class="recette">tomato, mozarella, sweet peppers, North African sausage, egg</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Extra-charge of garnish </label><label class="recette"> </label><label class="prix">1</label></li>
			</ul>
		</div>
		<div id="tabs_pates">
			<ul>
				<li class="plat"><label  class="nom_plat" >Neapolitan-style spaghetti </label><label class="recette">tomato and basil</label><label class="prix">12</label></li>
				<li class="plat"><label  class="nom_plat" >Tagliatelle with cream and mushrooms </label><label class="recette">fresh cream and cultivated mushrooms</label><label class="prix">13</label></li>
				<li class="plat"><label  class="nom_plat" >Linguine al pesto </label><label class="recette">fresh cream and basil pesto</label><label class="prix">13</label></li>
				<li class="plat"><label  class="nom_plat" >Bolognese-syle spaghetti </label><label class="recette">tomato and minced meat</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Spaghetti with olive oil, garlic and red pepper </label><label class="recette">olive oil, garlic and red pepper</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Tagliatelle "à la carbonara" </label><label class="recette">fresh cream, lardoons and egg yolk</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Penne with four cheeses </label><label class="recette"> </label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Penne with tuna </label><label class="recette">fresh cream with tomato, tuna and onions</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Penne with  salmon </label><label class="recette">fresh cream and smocked salmon</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Penne "à l'arrabiata" </label><label class="recette">tomato and red peppers</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Linguine alle vongole </label><label class="recette">clams, garlic adn olive oil</label><label class="prix">22</label></li>
				<li class="plat"><label  class="nom_plat" >Linguine with vegetables </label><label class="recette">olive oil, artichokes, aubergines and courgettes</label><label class="prix">15</label></li>
			</ul>
		</div>		
		<div id="tabs_plats">
			<ul>
				<li class="plat"><label  class="nom_plat" >Milanese-style escalope </label><label class="recette">breaded veal escalope, neapolitan-style spaghetti</label><label class="prix">19</label></li>
				<li class="plat"><label  class="nom_plat" >Beef tagliata </label><label class="recette">grilled and thinly-sliced heart of rump steak, rocket salad, Parmesan</label><label class="prix">20</label></li>
				<li class="plat"><label  class="nom_plat" >Fillet of sea bream, virgin sauce </label><label class="prix">19</label></li>
				<li class="plat"><label class="recette">olive oil marinade, fresh tomatoes and black olives with fresh spinach</label></li>
				<li class="plat"><label  class="nom_plat" >Calamari fritti </label><label class="recette">fried squid, rocket salad and tartare sauce</label><label class="prix">18</label></li>
			</ul>
		</div>		
		<div id="tabs_desserts">		
			<ul>
				<li class="plat"><label  class="nom_plat" >Pannacota </label><label class="recette"> and red fruits coulis</label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Chocolate mousse </label><label class="recette"> </label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Tiramisu </label><label class="recette"></label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Caramelized custard cream </label><label class="recette"> </label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Small rum babas </label><label class="recette">whipped cream</label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Cup of red fruits </label><label class="recette"> (according to season)</label><label class="prix">12</label></li>
				<li class="plat"><label  class="nom_plat" >Cup of red fruits in Melba </label><label class="prix">14</label></li>
				<li class="plat"><label class="recette">(selon saison) red fruits on a scope of vanilla ice cream, whipped cream and red fruits coulis</label></li>
				<li class="plat"><label  class="nom_plat" >Tart of the day </label><label class="recette"> </label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Strawberries tart </label><label class="recette">(according to season)</label><label class="prix">9</label></li>
				<li class="plat"><label  class="nom_plat" >Fresh fruits salad </label><label class="recette"></label><label class="prix">8</label></li>
				<li class="plat"><label  class="nom_plat" >Fresh fruits salad in Melba</label><label class="prix">12</label></li>
				<li class="plat"><label  class="recette">fruits salad on a scope of vanilla ice cream, whipped cream and red fruits coulis</label></li>
				<li class="plat"><label  class="nom_plat" >Gourmet coffee</label><label class="recette"> </label><label class="prix">9</label></li>
				<li class="plat"><label  class="nom_plat" >Gourmet tea</label><label class="recette"> or </label><label  class="nom_plat" >Gourmet infusion</label><label class="recette"> </label><label class="prix">11</label></li>
				<li class="plat"><label  class="nom_plat" >Iced nougat </label><label class="recette">red fruits coulis</label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Iced coffee mousse </label><label class="recette"> </label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Vanilla "Mystère" </label><label class="recette"></label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Ice creams and sorbets </label><label class="recette">2 flavours, iced cups on ice cream menu</label><label class="prix">7</label></li>
			</ul>
		</div>		
		<div id="tabs_vins">				
				<label style="font-size: 20px; color: black;">Wines in pitchers</label></br>
				<ul>
					<li class="plat" style="font-family: Times New Roman;"><label  class="nom_plat" style="color: #e73434; font-size: 20px;">White wines</label><label class="prix" style="margin-left: 20px; font-size: 12px;">50cl.</label><label class="prix" style="margin-left: 10px; font-size: 12px;">25cl.</label><label class="prix" style="margin-left: 10px; font-size: 12px;">Verre 16cl.</label></li>
					<li class="plat"><label  class="nom_plat">Bourgogne-Aligoté </label><label class="recette">aoc</label><label class="prix" style="margin-right: 10px;">16</label><label class="prix" style="margin-right: 30px;">8</label><label class="prix" style="margin-right: 30px;">5</label></li>
					<li class="plat"><label  class="nom_plat">Sancerre </label><label class="recette">aoc Les Broux</label><label class="prix" style="margin-right: 10px;">24</label><label class="prix" style="margin-right: 30px;">12</label><label class="prix" style="margin-right: 20px;">6.6</label></li>
					<li class="plat"><label  class="nom_plat">Orvieto Classico </label><label class="recette">d.o.c Uggiano</label><label class="prix" style="margin-right: 10px;">16</label><label class="prix" style="margin-right: 30px;">8</label><label class="prix" style="margin-right: 30px;">5</label></li>
					<li class="plat"><label  class="nom_plat">Spumante Prosecco </label><label class="recette">Martini </label><label class="prix" style="margin-right: 10px;">22</label><label class="prix" style="margin-right: 30px;">11</label><label class="prix" style="margin-right: 22px;">6</label></li>
					</br>
					<li class="plat" style="font-family: Times New Roman;"><label  class="nom_plat" style="color: #e73434; font-size: 20px;">Rosé Wines</label></li>
					<li class="plat"><label  class="nom_plat">Côte de Provence </label><label class="recette">aoc Côté Presqu'Île, Minuty</label><label class="prix" style="margin-right: 10px;">22</label><label class="prix" style="margin-right: 30px;">11</label><label class="prix" style="margin-right: 20px;">6.2</label></li>
					<li class="plat"><label  class="nom_plat">Bardolino Chiaretto </label><label class="recette">d.o.c Delibori</label><label class="prix" style="margin-right: 10px;">16</label><label class="prix" style="margin-right: 30px;">8</label><label class="prix" style="margin-right: 30px;">5</label></li>
					</br>
					<li class="plat" style="font-family: Times New Roman;"><label  class="nom_plat" style="color: #e73434; font-size: 20px;">Red Wines</label></li>
					<li class="plat"><label  class="nom_plat">Bordeaux </label><label class="recette">aoc Le Sabley</label><label class="prix" style="margin-right: 10px;">16</label><label class="prix" style="margin-right: 30px;">8</label><label class="prix" style="margin-right: 30px;">5</label></li>
					<li class="plat"><label  class="nom_plat">Brouilly </label><label class="recette">aoc Noël Briday</label><label class="prix" style="margin-right: 10px;">16</label><label class="prix" style="margin-right: 30px;">8</label><label class="prix" style="margin-right: 30px;">5</label></li>
					<li class="plat"><label  class="nom_plat">Bardolino </label><label class="recette">d.o.c Deibori</label><label class="prix" style="margin-right: 10px;">16</label><label class="prix" style="margin-right: 30px;">8</label><label class="prix" style="margin-right: 30px;">5</label></li>
					<li class="plat"><label  class="nom_plat">Chianti Classico </label><label class="recette">d.o.c.g Falco di Neri</label><label class="prix" style="margin-right: 10px;">24</label><label class="prix" style="margin-right: 30px;">12</label><label class="prix" style="margin-right: 20px;">6.7</label></li>
					<li class="plat"><label  class="nom_plat">Lambrusco Dolce </label><label class="recette">d.o.c Medici Ermete <i>(rouge pétillant)</i></label><label class="prix" style="margin-right: 10px;">24</label><label class="prix" style="margin-right: 30px;">12</label><label class="prix" style="margin-right: 20px;">6.7</label></li>
				</ul>
				</br>
				<label style="font-size: 20px; color: black;">Wines in bottles</label></br>
				<ul>
					<li class="plat" style="font-family: Times New Roman;"><label  class="nom_plat" style="color: #e73434; font-size: 20px;">Red</label><label class="prix" style="font-size: 12px; margin-right: 10px;">75cl.</label></li>
					<li class="plat"><label  class="nom_plat">Bordeaux </label><label class="recette">aoc Le Bordeaux de Barbe</label><label class="prix" style="margin-right: 10px;">21</label></li>
					<li class="plat"><label  class="nom_plat">Côtes de Provence </label><label class="recette">aoc Minuty Prestige</label><label class="prix" style="margin-right: 10px;">40</label></li>
					<li class="plat"><label  class="nom_plat">Bardolino </label><label class="recette">d.o.c Delibori</label><label class="prix" style="margin-right: 10px;">24</label></li>
					<li class="plat"><label  class="nom_plat">Valpolicella </label><label class="recette">d.o.c Terre di Verona </label><label class="prix" style="margin-right: 10px;">26</label></li>
					<li class="plat"><label  class="nom_plat">Chianti Classico </label><label class="recette">d.o.c.g Falco di Neri </label><label class="prix" style="margin-right: 10px;">36</label></li>
					<li class="plat"><label  class="nom_plat">Nero d'Avola </label><label class="recette">igt Sicilia Mandrarossa</label><label class="prix" style="margin-right: 10px;">30</label></li>
					<li class="plat"><label  class="nom_plat">Lambrusco Dolce </label><label class="recette">d.o.c Medici Ermete <i>(rouge pétillant)</i>  </label><label class="prix" style="margin-right: 10px;">27</label></li>
					</br>
					<li class="plat" style="font-family: Times New Roman;"><label  class="nom_plat" style="color: #e73434; font-size: 20px;">Rosés</label></li>
					<li class="plat"><label  class="nom_plat">Côtes de Provence </label><label class="recette">aoc Minuty Prestige</label><label class="prix" style="margin-right: 10px;">40</label></li>
					<li class="plat"><label  class="nom_plat">Côtes de Provence </label><label class="recette">aoc Côté Presqu'Île, Minuty</label><label class="prix" style="margin-right: 10px;">33</label></li>
					<li class="plat"><label  class="nom_plat">Bardolino Chiaretto </label><label class="recette">d.o.c Delibori</label><label class="prix" style="margin-right: 10px;">24</label></li>
					</br>
					<li class="plat" style="font-family: Times New Roman;"><label  class="nom_plat" style="color: #e73434; font-size: 20px;">Blancs</label></li>
					<li class="plat"><label  class="nom_plat">Sancerre </label><label class="recette">aoc Les Broux</label><label class="prix" style="margin-right: 10px;">33</label></li>
					<li class="plat"><label  class="nom_plat">Côtes de Provence </label><label class="recette">aoc Minuty Prestige</label><label class="prix" style="margin-right: 10px;">40</label></li>
					<li class="plat"><label  class="nom_plat">Orvieto Classico </label><label class="recette">d.o.c Uggiano</label><label class="prix" style="margin-right: 10px;">25</label></li>
					<li class="plat"><label  class="nom_plat">Spumante Prosecco </label><label class="recette">d.o.c Martini</label><label class="prix" style="margin-right: 10px;">29</label></li>
				</ul>
		</div>
	</div>
</div>