<div class="tabs" role="tabpanel">
	<ul class="nav nav-tabs responsive" role="tablist" id="myTab">
		<li role="presentation" class="active"><a href="#starter" aria-controls="starter" role="tab" data-toggle="tab" class="type">Entrées</a></li>
		<li role="presentation"><a href="#pizza" aria-controls="pizza" role="tab" data-toggle="tab"><strong>Pizzas</strong></a></li>
		<li role="presentation"><a href="#pasta" aria-controls="pasta" role="tab" data-toggle="tab"><strong>Pâtes</a></strong></li>
		<li role="presentation"><a href="#misc" aria-controls="misc" role="tab" data-toggle="tab">Plats</a></li>
		<li role="presentation"><a href="#desert" aria-controls="desert" role="tab" data-toggle="tab">Desserts</a></li>
		<li role="presentation"><a href="#wine" aria-controls="wine" role="tab" data-toggle="tab">Vins</a></li>
	</ul>

	<div class="tab-content responsive">
		<div role="tabpanel" class="tab-pane active" id="starter">
			<ul>
				<li class="plat"><label  class="nom_plat" >Tomate mozzarella au basilic </label><label class="recette"> </label><label class="prix">12</label></li>
				<li class="plat"><label  class="nom_plat" >Antipasti de légumes à l'huile d'olive </label><label class="recette"> </label><label class="prix">12</label></li>
				<li class="plat"><label  class="nom_plat" >Salade de haricots verts frais </label><label class="recette"> </label><label class="prix">11</label></li>
				<li class="plat"><label  class="nom_plat" >Assiette de jambon de Parme </label><label class="recette"> </label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Assiette de charcuterie italienne </label><label class="recette">coppa, bresaola, jambon de Parme </label><label class="prix">17</label></li>
				<li class="plat"><label  class="nom_plat" >Bruschetta napolitaine </label><label class="recette"> </label><label class="prix">11</label></li>
				<li class="plat"><label  class="nom_plat" >Carpaccio de boeuf </label><label class="recette"> </label><label class="prix">13</label></li>
				<li class="plat"><label  class="nom_plat" >Saumon cru mariné à l'aneth </label><label class="recette"> </label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Salade Bacino </label><label class="recette">roquette, Parmesan et tomates séchées</label><label class="prix">11</label></li>
				<li class="plat"><label  class="nom_plat" >Supplement boule de mozzarella </label><label class="recette"></label><label class="prix">5</label></li>
			</ul>
		</div>
		<div role="tabpanel" class="tab-pane" id="pizza">
			<ul>
				<li class="plat"><label  class="nom_plat" >Pizza blanche à l'ail et l'huile d'olive </label><label class="recette"> </label><label class="prix">8</label></li>
				<li class="plat"><label  class="nom_plat" >Margharita </label><label class="recette">tomate, mozarella, olives</label><label class="prix">13</label></li>
				<li class="plat"><label  class="nom_plat" >Napolitaine </label><label class="recette">tomate, mozarella, olives, anchois</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Quatre fromages </label><label class="recette">tomate, mozarella, Gorgonzola, chèvre, Emmental</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Regina </label><label class="recette">tomate, mozarella, jambon, champignons</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Quatre saisons </label><label class="recette">tomate, mozarella, olives, jambon, champignons, artichauts</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Al tonno </label><label class="recette">tomates, thon, olives, câpres</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Calzone </label><label class="recette">tomate, mozarella, jambon, oeuf</label><label class="prix">14</label></li>
				<li class="plat"><label  class="nom_plat" >Parma </label><label class="recette">tomate, mozarella, jambon de Parme, crème fraîche</label><label class="prix">17</label></li>
				<li class="plat"><label  class="nom_plat" >Chorizo </label><label class="recette">tomate, mozarella, chorizo, oignons, oeuf</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Salmone </label><label class="recette">tomate, mozarella, saumon fumé, crème fraîche</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Bacino </label><label class="recette">tomate, mozarella, roquette fraîche, tomates fraîches marinées</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Campione </label><label class="recette">tomate, mozarella, viande hachée, oignons et oeuf</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Végétarienne </label><label class="recette">tomate, mozarella, champignons, courgettes et aubergines</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Orientale </label><label class="recette">tomate, mozarella, poivrons, merguez, oeuf</label><label class="prix">15</label></li>
				<li class="plat"><label  class="nom_plat" >Supplément garniture </label><label class="recette"> </label><label class="prix">1</label></li>
			</ul>
		</div>

		<div role="tabpanel" class="tab-pane" id="pasta">
		<ul>
			<li class="plat"><label  class="nom_plat" >Spaghetti à la Napolitaine </label><label class="recette">tomate et basilic</label><label class="prix">12</label></li>
			<li class="plat"><label  class="nom_plat" >Tagliatelle à la crème et aux champignons </label><label class="recette">crème fraîche et champignons de Paris</label><label class="prix">13</label></li>
			<li class="plat"><label  class="nom_plat" >Linguine al pesto </label><label class="recette">crème fraîche et pesto de basilic</label><label class="prix">13</label></li>
			<li class="plat"><label  class="nom_plat" >Spaghetti à la Bolognaise </label><label class="recette">tomate et viande hachée</label><label class="prix">14</label></li>
			<li class="plat"><label  class="nom_plat" >Spaghetti à l'huile d'olive, ail et piments </label><label class="recette">huile d'olive, ail et piments</label><label class="prix">14</label></li>
			<li class="plat"><label  class="nom_plat" >Tagliatelle à la carbonara </label><label class="recette">crème fraîche, lardon, jaune d'oeuf</label><label class="prix">14</label></li>
			<li class="plat"><label  class="nom_plat" >Penne aux quatre fromages </label><label class="recette"> </label><label class="prix">14</label></li>
			<li class="plat"><label  class="nom_plat" >Penne au thon </label><label class="recette">crème fraîche tomatée, thon et oignons</label><label class="prix">14</label></li>
			<li class="plat"><label  class="nom_plat" >Penne au saumon </label><label class="recette">crème fraîche et saumon fumé</label><label class="prix">15</label></li>
			<li class="plat"><label  class="nom_plat" >Penne à l'arrabiata </label><label class="recette">tomate et piments</label><label class="prix">14</label></li>
			<li class="plat"><label  class="nom_plat" >Linguine alle vongole </label><label class="recette">palourdes, ail et huile d'olive</label><label class="prix">22</label></li>
			<li class="plat"><label  class="nom_plat" >Linguine aux légumes </label><label class="recette">huile d'olive, artichauts, aubergines et courgettes</label><label class="prix">15</label></li>
		</ul>
		</div>
		
		<div role="tabpanel" class="tab-pane" id="misc">
		<ul>
			<li class="plat"><label  class="nom_plat" >Escalope à la Milanaise </label><label class="recette">escalope de veau panée, spaghetti napolitaine</label><label class="prix">19</label></li>
			<li class="plat"><label  class="nom_plat" >Tagliata de boeuf </label><label class="recette">coeur de rumsteak grillé et émincé, roquette et Parmesan</label><label class="prix">20</label></li>
			<li class="plat"><label  class="nom_plat" >Filet de dorade, sauce vierge </label><label class="prix">19</label></li>
			<li class="plat"><label class="recette">marinade à l'huile d'olive, tomate fraîche et olives noires avec des épinards frais </label></li>
			<li class="plat"><label  class="nom_plat" >Calamari fritti </label><label class="recette">friture de calamars, sauce tartare</label><label class="prix">18</label></li>
		</ul>
		</div>
		
		<div role="tabpanel" class="tab-pane" id="desert">
			<ul>
				<li class="plat"><label  class="nom_plat" >Pannacota </label><label class="recette"> coulis de fruit rouge</label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Mousse au chocolat </label><label class="recette"> </label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Tiramisu </label><label class="recette">maison</label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Crème brûlée </label><label class="recette"> </label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Petits babas au rhum </label><label class="recette">crème Chantilly</label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Coupe de fruits rouges </label><label class="recette"> (selon saison)</label><label class="prix">12</label></li>
				<li class="plat"><label  class="nom_plat" >Coupe de fruits rouges en Melba </label><label class="prix">14</label></li>
				<li class="plat"><label class="recette">(selon saison) fruits rouges, chantilly, glace vanille et coulis de fruits rouges</label></li>
				<li class="plat"><label  class="nom_plat" >Tarte du jour </label><label class="recette"> </label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Tarte aux fraises </label><label class="recette">(selon saison)</label><label class="prix">9</label></li>
				<li class="plat"><label  class="nom_plat" >Salade de fruits frais </label><label class="recette">selon saison</label><label class="prix">8</label></li>
				<li class="plat"><label  class="nom_plat" >Salade de fruits frais en Melba </label><label class="prix">12</label></li>
				<li class="plat"><label class="recette">salade de fruits, chantilly, glace vanille et coulis de fruits rouges</label></li>
				<li class="plat"><label  class="nom_plat" >Café gourmand </label><label class="recette"> </label><label class="prix">9</label></li>
				<li class="plat"><label  class="nom_plat" >Thé gourmand</label><label class="recette"> ou </label><label  class="nom_plat" >Infusion gourmande</label><label class="recette"> </label><label class="prix">11</label></li>
				<li class="plat"><label  class="nom_plat" >Nougat glacé </label><label class="recette">coulis de fruits rouges</label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Parfait au café </label><label class="recette"> </label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Mystère à la vanille </label><label class="recette">à la vanille</label><label class="prix">7</label></li>
				<li class="plat"><label  class="nom_plat" >Glaces et sorbets </label><label class="recette">2 parfums, voir la carte des glaces pour les coupes glacées</label><label class="prix">7</label></li>
			</ul>
		</div>		
		<div role="tabpanel" class="tab-pane" id="wine" >
				<label style="font-size: 20px; color: black;">Vins en pichets</label></br>
				<ul>
					<li class="plat" style="font-family: Times New Roman;"><label  class="nom_plat" style="color: #e73434; font-size: 20px;">Blancs</label><label class="prix" style="margin-left: 20px; font-size: 12px;">50cl.</label><label class="prix" style="margin-left: 10px; font-size: 12px;">25cl.</label><label class="prix" style="margin-left: 10px; font-size: 12px;">Verre 16cl.</label></li>
					<li class="plat"><label  class="nom_plat">Bourgogne-Aligoté </label><label class="recette">aoc</label><label class="prix" style="margin-right: 10px;">16</label><label class="prix" style="margin-right: 30px;">8</label><label class="prix" style="margin-right: 30px;">5</label></li>
					<li class="plat"><label  class="nom_plat">Sancerre </label><label class="recette">aoc Les Broux</label><label class="prix" style="margin-right: 10px;">24</label><label class="prix" style="margin-right: 30px;">12</label><label class="prix" style="margin-right: 20px;">6.6</label></li>
					<li class="plat"><label  class="nom_plat">Orvieto Classico </label><label class="recette">d.o.c Uggiano</label><label class="prix" style="margin-right: 10px;">16</label><label class="prix" style="margin-right: 30px;">8</label><label class="prix" style="margin-right: 30px;">5</label></li>
					<li class="plat"><label  class="nom_plat">Spumante Prosecco </label><label class="recette">Martini </label><label class="prix" style="margin-right: 10px;">22</label><label class="prix" style="margin-right: 30px;">11</label><label class="prix" style="margin-right: 22px;">6</label></li>
					</br>
					<li class="plat" style="font-family: Times New Roman;"><label  class="nom_plat" style="color: #e73434; font-size: 20px;">Rosés</label></li>
					<li class="plat"><label  class="nom_plat">Côte de Provence </label><label class="recette">aoc Côté Presqu'Île, Minuty</label><label class="prix" style="margin-right: 10px;">22</label><label class="prix" style="margin-right: 30px;">11</label><label class="prix" style="margin-right: 20px;">6.2</label></li>
					<li class="plat"><label  class="nom_plat">Bardolino Chiaretto </label><label class="recette">d.o.c Delibori</label><label class="prix" style="margin-right: 10px;">16</label><label class="prix" style="margin-right: 30px;">8</label><label class="prix" style="margin-right: 30px;">5</label></li>
					</br>
					<li class="plat" style="font-family: Times New Roman;"><label  class="nom_plat" style="color: #e73434; font-size: 20px;">Rouges</label></li>
					<li class="plat"><label  class="nom_plat">Bordeaux </label><label class="recette">aoc Le Sabley</label><label class="prix" style="margin-right: 10px;">16</label><label class="prix" style="margin-right: 30px;">8</label><label class="prix" style="margin-right: 30px;">5</label></li>
					<li class="plat"><label  class="nom_plat">Brouilly </label><label class="recette">aoc Noël Briday</label><label class="prix" style="margin-right: 10px;">16</label><label class="prix" style="margin-right: 30px;">8</label><label class="prix" style="margin-right: 30px;">5</label></li>
					<li class="plat"><label  class="nom_plat">Bardolino </label><label class="recette">d.o.c Deibori</label><label class="prix" style="margin-right: 10px;">16</label><label class="prix" style="margin-right: 30px;">8</label><label class="prix" style="margin-right: 30px;">5</label></li>
					<li class="plat"><label  class="nom_plat">Chianti Classico </label><label class="recette">d.o.c.g Falco di Neri</label><label class="prix" style="margin-right: 10px;">24</label><label class="prix" style="margin-right: 30px;">12</label><label class="prix" style="margin-right: 20px;">6.7</label></li>
					<li class="plat"><label  class="nom_plat">Lambrusco Dolce </label><label class="recette">d.o.c Medici Ermete <i>(rouge pétillant)</i></label><label class="prix" style="margin-right: 10px;">24</label><label class="prix" style="margin-right: 30px;">12</label><label class="prix" style="margin-right: 20px;">6.7</label></li>					
			</ul>
			</br>
			<label style="font-size: 20px; color: black;">Vins en Bouteilles</label></br>
			<ul>
					<li class="plat" style="font-family: Times New Roman;"><label  class="nom_plat" style="color: #e73434; font-size: 20px;">Rouges</label><label class="prix" style="font-size: 12px; margin-right: 10px;">75cl.</label></li>
					<li class="plat"><label  class="nom_plat">Bordeaux </label><label class="recette">aoc Le Bordeaux de Barbe</label><label class="prix" style="margin-right: 10px;">21</label></li>
					<li class="plat"><label  class="nom_plat">Côtes de Provence </label><label class="recette">aoc Minuty Prestige</label><label class="prix" style="margin-right: 10px;">40</label></li>
					<li class="plat"><label  class="nom_plat">Bardolino </label><label class="recette">d.o.c Delibori</label><label class="prix" style="margin-right: 10px;">24</label></li>
					<li class="plat"><label  class="nom_plat">Valpolicella </label><label class="recette">d.o.c Terre di Verona </label><label class="prix" style="margin-right: 10px;">26</label></li>
					<li class="plat"><label  class="nom_plat">Chianti Classico </label><label class="recette">d.o.c.g Falco di Neri </label><label class="prix" style="margin-right: 10px;">36</label></li>
					<li class="plat"><label  class="nom_plat">Nero d'Avola </label><label class="recette">igt Sicilia Mandrarossa</label><label class="prix" style="margin-right: 10px;">30</label></li>
					<li class="plat"><label  class="nom_plat">Lambrusco Dolce </label><label class="recette">d.o.c Medici Ermete <i>(rouge pétillant)</i>  </label><label class="prix" style="margin-right: 10px;">27</label></li>	
					</br>
					<li class="plat" style="font-family: Times New Roman;"><label  class="nom_plat" style="color: #e73434; font-size: 20px;">Rosés</label></li>
					<li class="plat"><label  class="nom_plat">Côtes de Provence </label><label class="recette">aoc Minuty Prestige</label><label class="prix" style="margin-right: 10px;">40</label></li>
					<li class="plat"><label  class="nom_plat">Côtes de Provence </label><label class="recette">aoc Côté Presqu'Île, Minuty</label><label class="prix" style="margin-right: 10px;">33</label></li>
					<li class="plat"><label  class="nom_plat">Bardolino Chiaretto </label><label class="recette">d.o.c Delibori</label><label class="prix" style="margin-right: 10px;">24</label></li>
					</br>
					<li class="plat" style="font-family: Times New Roman;"><label  class="nom_plat" >Blancs</label></li>
					<li class="plat"><label  class="nom_plat">Sancerre </label><label class="recette">aoc Les Broux</label><label class="prix" style="margin-right: 10px;">33</label></li>
					<li class="plat"><label  class="nom_plat">Côtes de Provence </label><label class="recette">aoc Minuty Prestige</label><label class="prix" >40</label></li>
					<li class="plat"><label  class="nom_plat">Orvieto Classico </label><label class="recette">d.o.c Uggiano</label><label class="prix" >25</label></li>
					<li class="plat"><label  class="nom_plat">Spumante Prosecco </label><label class="recette">d.o.c Martini</label><label class="prix">29</label></li>					
			</ul>
		</div>
	</div>
</div>
