<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Pizza, pâtes, spécialités italiennes." />
		<title>Bacino</title>
		<style type="text/css">	</style>
		<link rel="stylesheet" href="/ressources/css/style.css" />	
		<link href="/ressources/bootstrap/css/bootstrap.min.css" rel="stylesheet">	
	</head>
	<body>
		<header class="top index">	
			<div class="container">
				<h1>Page d'acceuil</h1>
				<div id="rouge">
					<div id="logo_index_div">
						<img id="logo_index" src="ressources/images/logo/logo_gris.png" alt="Bacino"></img><br>
						<h1 id="motto">Pizzas &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Pâtes &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Spécialités italiennes</h1>
					</div>
				</div>
				<div id="marquise">
					<img id="img_marquise" src="/ressources/images/marquise.png" alt="Bacino"></img>
				</div>
				<nav class="index-nav navbar-collapse collapse.in" role="navigation">
		            <ul class="navbar-nav nav">
		                <li><a id="menuCarte" class="menu" href="/carte/index">La Carte</a></li>
		                <li><a id="menuPhotos" class="menu" href="/site/photo" >Photos</a></li>
		                <li><a id="menuAcces" class="menu" href="/site/acces">Accès</a></li>
		                <li><a id="menuContact" class="menu" href="/site/contact">Contact</a></li>
		            </ul>
   				</nav>			
			</div>
    		
		</header>
		<div class="middle">
		</div>
		<div class="bottom">
			<div class="container">
				<label>121, rue de Courcelles - 75017 Paris • 01 43 80 11 68 • Ouvert tous les jours Midis et Soirs</label> •
				<a href="https://www.facebook.com/restaurantbacino">
					<img  id="logo_facebook"  src="/ressources/images/FB-f-Logo__white_29.png" alt="facebook">
				</a>
			</div>
		</div>		
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>	
		<script src="/ressources/bootstrap/js/bootstrap.min.js"></script>
		<script src="/ressources/bootstrap/js/responsive-tabs.js"></script>
		<script src="/ressources/js/app.js"></script>
	</body>
</html>
