<div class="middle">
	<div class="container">
		<h1>Acces</h1>
		<div id="transports">
			Accès en transports:
			<ul>
				<li class="acces"><img class="metro" src="/ressources/images/M_2.png" alt="2" title="Ligne 2">  <label>Courcelles</label> </li>
				<li class="acces"><img class="metro" src="/ressources/images/M_3.png" alt="3" title="Ligne 3">  <label>Pereire</label> </li>
				<li class="acces"><img class="metro" src="/ressources/images/RER_C.png" alt="c" title="RER C">  <label>Pereire - Levallois</label> </li>
			</ul>
		</div>
		<div id="carte">
			<iframe width="1000" height="460" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=fr&amp;geocode=&amp;q=121+Rue+de+Courcelles,+Paris,+France&amp;aq=0&amp;oq=121rue&amp;sll=37.0625,-95.677068&amp;sspn=39.916234,86.572266&amp;ie=UTF8&amp;hq=&amp;hnear=121+Rue+de+Courcelles,+75017+Paris,+France&amp;t=m&amp;ll=48.883288,2.300123&amp;spn=0.002469,0.010729&amp;z=17&amp;output=embed"></iframe><br />
		</div>
	</div>
</div>