<div class="middle">
	<div class="container">
		<h1>Contact</h1>
		<div id="contact">
			<p id="adresse">Adresse: Restaurant <strong>Bacino</strong>, 121 <strong>rue de Courcelles</strong> 75017 Paris</p>
			<p id="tel">Téléphone: 01 43 80 11 68</br>Pour réserver ou commander à <strong>emporter</strong></p>
			<p id="ouvert">Ouvert <strong>tous les jours</strong> de 12h à 15h et de 19h15 à 23h</p>
			<p id="bonus">Salle climatisée - Wi-Fi</p>
		</div>
	</div>
</div>			