<div class="middle">
	<div class="container">	
	<h1>Photos</h1>
		<div id="fotorama">
			<div class="fotorama" data-width="700" data-ratio="700/500" data-max-width="100%">
				<img  src="/ressources/photos/1.jpg" alt="1">
				<img  src="/ressources/photos/2.jpg" alt="2">
				<img  src="/ressources/photos/3.jpg" alt="3">
				<img  src="/ressources/photos/4.jpg" alt="4">
				<img  src="/ressources/photos/5.jpg" alt="5">
				<img  src="/ressources/photos/6.jpg" alt="6">
				<img  src="/ressources/photos/7.jpg" alt="7">
				<img  src="/ressources/photos/8.jpg" alt="8">		
			</div>
		</div>
	</div>
</div>